
COMPLETED_OPERATION_INDICATOR = "images/arkn_stage_completed_indicator_1.png"
COMPLETED_ANNIHILATION_INDICATOR_1 = "images/arkn_annihilation_completed_indicator_1.png"
COMPLETED_ANNIHILATION_INDICATOR_2 = "images/arkn_annihilation_completed_indicator_2.png"
