FARM_EXP_ENTRY = "images/arkn_farm_exp_btn.png"
FARM_MONEY_ENTRY = "images/arkn_farm_money_btn.png"
FARM_TALENT_BOOK_ENTRY = "images/arkn_farm_skill_book_btn.png"
FARM_MEDIC_DEFENDER_ENTRY = "images/arkn_farm_medic_defender_btn.png"
FARM_GUARD_SPECIALIST_ENTRY = "images/arkn_farm_guard_specialist_btn.png"
FARM_VANGUARD_SUPPORTER_ENTRY = "images/arkn_farm_vanguard_supporter_btn.png"
FARM_SNIPER_CASTER_ENTRY = "images/arkn_farm_sniper_caster_btn.png"
