FARM_CA5_TALENT_BOOK_BUTTON = "images/arkn_farm_ca5.png"
FARM_CE6_MONEY_BUTTON = "images/arkn_farm_ce6.png"
FARM_LS6_EXP_BUTTON = "images/arkn_farm_ls6.png"
PREPARE_OPERATION_BUTTON = "images/arkn_start_operation.png"
FARM_PRB2_SNIPER_CASTER_BUTTON = "images/arkn_farm_prb2.png"
FARM_PRD2_GUARD_SPECIALIST_BUTTON = "images/arkn_farm_prd2.png"
FARM_PRC2_VANGUARD_SUPPORTER_BUTTON = "images/arkn_farm_prc2.png"
FARM_PRA2_DEFENDER_MEDIC_BUTTON = "images/arkn_farm_pra2.png"
