FARM_CA5_TALENT_BOOK_BUTTON = "images/arkn_farm_ca5.png"
FARM_CE5_MONEY_BUTTON = "images/arkn_farm_ce5.png"
FARM_LS5_EXP_BUTTON = "images/arkn_farm_ls5.png"
PREPARE_OPERATION_BUTTON = "images/arkn_start_operation.png"
FARM_PRB2_SNIPER_CASTER_BUTTON = "images/arkn_farm_prb2.png"
FARM_PRD2_GUARD_SPECIALIST_BUTTON = "images/arkn_farm_prd2.png"
